name: Main workflow

on:
  pull_request:
  push:
  schedule:
    - cron: 0 0 * * 5

jobs:
  plugin_test:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install packages on macOS
        run: brew install automake readline
        if: matrix.os == 'macos-latest'

      - name: Install packages on Ubuntu
        run: sudo apt-get install libreadline-dev
        if: matrix.os == 'ubuntu-latest'

      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: rlwrap --version

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up asdf
        uses: asdf-vm/actions/setup@v1

      - name: Install bats-core
        run: brew install bats-core

      - name: Test plugin
        run: |
          asdf plugin-add rlwrap $GITHUB_WORKSPACE
          make test
        env:
          GITHUB_API_TOKEN: ${{ github.token }}

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install shellcheck
        run: brew install shellcheck

      - name: Run ShellCheck
        run: make lint

  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install shfmt
        run: brew install shfmt

      - name: Run shfmt
        run: make fmt-check
